### ISSUE TITLE
Reloading server causes Blaze Burners to go out.

### ISSUE THREAD

**Issue by Greg-J** [ferriarnus/LiquidBurner#7]
When a boiler using a Blaze Burner that has lava pumped directly into it reloads, the burner is turned off and the boiler is has to be restarted by another power source. This is on Fabric 1.19.2.

Whatever `create:blaze_heater` is, it doesn't exist.

`[11:37:27] [Server thread/ERROR]: Failed to load data for block entity create:blaze_heater
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1937.method_8433()" because "this.field_11863" is null
        at com.simibubi.create.content.processing.burner.BlazeBurnerBlockEntity.recipeFluids(BlazeBurnerBlockEntity.java:561) ~[create-fabric-0.5.1-c-build.1160+mc1.19.2.jar:?]
        at com.simibubi.create.content.processing.burner.BlazeBurnerBlockEntity.mddfc1fc$liquidburner$lambda$new$0$2(BlazeBurnerBlockEntity.java:542) ~[create-fabric-0.5.1-c-build.1160+mc1.19.2.jar:?]
        at com.simibubi.create.foundation.fluid.SmartFluidTank.setFluid(SmartFluidTank.java:35) ~[create-fabric-0.5.1-c-build.1160+mc1.19.2.jar:?]
        at com.simibubi.create.foundation.fluid.SmartFluidTank.setFluid(SmartFluidTank.java:29) ~[create-fabric-0.5.1-c-build.1160+mc1.19.2.jar:?]
        at io.github.fabricators_of_create.porting_lib.transfer.fluid.FluidTank.readFromNBT(FluidTank.java:99) ~[porting_lib_transfer-2.1.1096+1.19.2-d26e68552589437.jar:?]
        at com.simibubi.create.content.processing.burner.BlazeBurnerBlockEntity.handler$dhk000$liquidburner$appendRead(BlazeBurnerBlockEntity.java:631) ~[create-fabric-0.5.1-c-build.1160+mc1.19.2.jar:?]
        at com.simibubi.create.content.processing.burner.BlazeBurnerBlockEntity.read(BlazeBurnerBlockEntity.java) ~[create-fabric-0.5.1-c-build.1160+mc1.19.2.jar:?]
        at com.simibubi.create.foundation.blockEntity.SmartBlockEntity.method_11014(SmartBlockEntity.java:119) ~[create-fabric-0.5.1-c-build.1160+mc1.19.2.jar:?]
        at net.minecraft.class_2586.method_17897(class_2586.java:132) ~[server-intermediary.jar:?]
        at java.util.Optional.map(Optional.java:260) ~[?:?]
        at net.minecraft.class_2586.method_11005(class_2586.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.class_2852.method_39797(class_2852.java:428) ~[server-intermediary.jar:?]
        at net.minecraft.class_2818.method_12206(class_2818.java:434) ~[server-intermediary.jar:?]
        at net.minecraft.class_3898.method_17227(class_3898.java:745) ~[server-intermediary.jar:?]
        at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-5.0.28.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
        at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-5.0.28.jar:?]
        at net.minecraft.class_3898.method_20460(class_3898.java:733) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:557) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:566) ~[server-intermediary.jar:?]
        at net.minecraft.class_3215.method_19492(class_3215.java:279) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$znh000$carpet$modifiedRunLoop(MinecraftServer.java:5394) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[11:37:27] [Server thread/WARN]: Skipping BlockEntity with id create:blaze_heater`

**Comment by ferriarnus** [comment]
I have released a new version that *should* solve this issue

**Comment by Greg-J** [comment]
> I have released a new version that _should_ solve this issue

Not for Fabric 1.19.2 though

**Comment by ferriarnus** [comment]
Oh missed that one, should be up now?

**Comment by tofo2** [comment]
same her with forge 1.20.1
